<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-12-02">

<title>Ejercicios de ACP y MDS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="practica6_files/libs/clipboard/clipboard.min.js"></script>
<script src="practica6_files/libs/quarto-html/quarto.js"></script>
<script src="practica6_files/libs/quarto-html/popper.min.js"></script>
<script src="practica6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="practica6_files/libs/quarto-html/anchor.min.js"></script>
<link href="practica6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="practica6_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="practica6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="practica6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="practica6_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#problema-1" id="toc-problema-1" class="nav-link active" data-scroll-target="#problema-1">Problema 1</a>
  <ul class="collapse">
  <li><a href="#apartado-a" id="toc-apartado-a" class="nav-link" data-scroll-target="#apartado-a">Apartado a</a></li>
  <li><a href="#apartado-b" id="toc-apartado-b" class="nav-link" data-scroll-target="#apartado-b">Apartado b</a></li>
  <li><a href="#problema-2" id="toc-problema-2" class="nav-link" data-scroll-target="#problema-2">Problema 2</a>
  <ul class="collapse">
  <li><a href="#gráfico-para-vh" id="toc-gráfico-para-vh" class="nav-link" data-scroll-target="#gráfico-para-vh">Gráfico para VH</a></li>
  <li><a href="#gráfico-para-sp" id="toc-gráfico-para-sp" class="nav-link" data-scroll-target="#gráfico-para-sp">Gráfico para SP</a></li>
  <li><a href="#gráfico-para-pm" id="toc-gráfico-para-pm" class="nav-link" data-scroll-target="#gráfico-para-pm">Gráfico para PM</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ejercicios de ACP y MDS</h1>
<p class="subtitle lead">20582- Análisis de Datos para el GMAT</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 2, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="problema-1" class="level1">
<h1>Problema 1</h1>
<p><strong>En el siguiente <a href="https://github.com/igmuib/Practica_AD/blob/main/problema1_ACP.csv">enlace</a> encontraréis datos de España correspondientes al año 2021, organizados en 7 variables: 4 relacionadas con el uso de las tecnologías de la información y la comunicación (TIC) en las empresas, y 3 vinculadas al uso de estas tecnologías por la población y al equipamiento tecnológico de los hogares. Las variables son las siguientes:</strong></p>
<p><code>ebroad</code>: porcentaje de empresas con acceso a Internet de banda ancha (broadband).</p>
<p><code>esales</code>: porcentaje de empresas que realizan ventas electrónicas.</p>
<p><code>esocmedia</code>: porcentaje de empresas que utilizan redes sociales.</p>
<p><code>eweb</code>: porcentaje de empresas con sitio web.</p>
<p><code>hbroad</code>: porcentaje de hogares con acceso a Internet de banda ancha.</p>
<p><code>hiacc</code>: porcentaje de hogares con acceso general a Internet, independientemente del tipo de conexión.</p>
<p><code>iuse</code>: porcentaje de individuos que utilizan Internet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_TIC <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"problema1_ACP.csv"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="apartado-a" class="level3">
<h3 class="anchored" data-anchor-id="apartado-a">Apartado a</h3>
<p><strong>Realizad un análisis exploratorio de los datos, acompañado de un resumen de las observaciones más relevantes en relación con el contexto del problema, para ello crea una variable <code>region</code> con los siguientes niveles:</strong></p>
<ul>
<li><p>Europa Occidental” = c(“BE”, “FR”, “DE”, “AT”, “NL”, “LU”, “IE”),</p></li>
<li><p>Europa del Sur” = c(“ES”, “IT”, “PT”, “EL”, “CY”, “MT”),</p></li>
<li><p>“Europa del Este” = c(“CZ”, “BG”, “HU”, “PL”, “RO”, “SK”),</p></li>
<li><p>“Países Nórdicos” = c(“DK”, “SE”, “FI”, “NO”),</p></li>
<li><p>“Países Bálticos” = c(“EE”, “LV”, “LT”)</p></li>
</ul>
<p><strong>Aseguraos de incluir, un análisis de la matriz de correlaciones.</strong></p>
<p>Agregamos la columna <code>region</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data_TIC <span class="ot">&lt;-</span> data_TIC <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">region =</span> <span class="fu">case_when</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    X <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"BE"</span>, <span class="st">"FR"</span>, <span class="st">"DE"</span>, <span class="st">"AT"</span>, <span class="st">"NL"</span>, <span class="st">"LU"</span>, <span class="st">"IE"</span>) <span class="sc">~</span> <span class="st">"Europa Occidental"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    X <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"ES"</span>, <span class="st">"IT"</span>, <span class="st">"PT"</span>, <span class="st">"EL"</span>, <span class="st">"CY"</span>, <span class="st">"MT"</span>) <span class="sc">~</span> <span class="st">"Europa del Sur"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    X <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"CZ"</span>, <span class="st">"BG"</span>, <span class="st">"HU"</span>, <span class="st">"PL"</span>, <span class="st">"RO"</span>, <span class="st">"SK"</span>,<span class="st">"HR"</span>,<span class="st">"SI"</span>) <span class="sc">~</span> <span class="st">"Europa del Este"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    X <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"DK"</span>, <span class="st">"SE"</span>, <span class="st">"FI"</span>, <span class="st">"NO"</span>) <span class="sc">~</span> <span class="st">"Países Nórdicos"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    X <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"EE"</span>, <span class="st">"LV"</span>, <span class="st">"LT"</span>) <span class="sc">~</span> <span class="st">"Países Bálticos"</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data_TIC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "X"         "ebroad"    "esales"    "esocmedia" "eweb"      "hbroad"   
[7] "hiacc"     "iuse"      "region"   </code></pre>
</div>
</div>
<p>Veamos las estadísticas descriptivas por región:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> data_TIC <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="fu">list</span>(<span class="at">mean =</span> mean, <span class="at">sd =</span> sd), <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>summary_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 15
  region ebroad_mean ebroad_sd esales_mean esales_sd esocmedia_mean esocmedia_sd
  &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt;        &lt;dbl&gt;
1 Europ…        97.6      1.72        21.7      9.12           67.3         8.16
2 Europ…        93        5.53        18        6.78           47.2         7.55
3 Europ…        94.7      4.89        19.8      5.64           66.5        11.8 
4 Paíse…        98        2.65        22        8.89           55.7         4.04
5 Paíse…        99        1.73        32        7.21           78.7         1.53
# ℹ 8 more variables: eweb_mean &lt;dbl&gt;, eweb_sd &lt;dbl&gt;, hbroad_mean &lt;dbl&gt;,
#   hbroad_sd &lt;dbl&gt;, hiacc_mean &lt;dbl&gt;, hiacc_sd &lt;dbl&gt;, iuse_mean &lt;dbl&gt;,
#   iuse_sd &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Definamos la matriz de correlaciones:</p>
<p>Visualizemos la matriz de correlaciones:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcorrplot</span>(R, <span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">type =</span> <span class="st">"lower"</span>, <span class="at">lab =</span> <span class="cn">TRUE</span>, <span class="at">lab_size =</span> <span class="dv">3</span>, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">title =</span> <span class="st">"Matriz de correlaciones"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica6_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico de la matriz de correlaciones refleja las relaciones entre las variables numéricas de los datos:</p>
<ul>
<li><p>Correlaciones altas:</p>
<ul>
<li>hbroad y hiacc (0.92): Existe una relación muy fuerte entre el porcentaje de hogares con acceso a Internet de banda ancha y el acceso general a Internet. Esto tiene sentido, ya que la banda ancha es la tecnología más utilizada para el acceso doméstico.</li>
<li>iuse y hiacc (0.84): El porcentaje de individuos que utilizan Internet está estrechamente relacionado con el acceso general a Internet en los hogares.</li>
<li>iuse y hbroad (0.78): Los hogares con banda ancha tienen un fuerte impacto en el uso de Internet por los individuos.</li>
</ul></li>
<li><p>Correlaciones moderadas:</p>
<ul>
<li>eweb y esocmedia (0.69): El uso de sitios web por parte de las empresas está moderadamente correlacionado con el uso de redes sociales. Esto sugiere que las empresas más digitalizadas tienden a adoptar múltiples tecnologías TIC.</li>
<li>esocmedia y iuse (0.76): El uso de redes sociales en las empresas parece estar relacionado con el uso generalizado de Internet en la población.</li>
<li>eweb y hbroad (0.62): Las empresas con sitios web tienden a estar en países con alta penetración de banda ancha.</li>
</ul></li>
<li><p>Correlaciones bajas o débiles:</p>
<ul>
<li>esales y eweb (0.17): La relación entre las ventas electrónicas y la presencia de sitios web en las empresas es débil. Esto podría indicar que tener un sitio web no siempre se traduce en ventas en línea.</li>
<li>ebroad con otras variables: La banda ancha en las empresas (ebroad) muestra una correlación baja con otras variables, lo que sugiere que su impacto puede estar menos relacionado con las tendencias digitales generales de la población y los hogares.</li>
</ul></li>
</ul>
<p>No se observan correlaciones negativas significativas, lo que indica que las variables están alineadas hacia el uso e integración de tecnologías.</p>
<p>Las tecnologías TIC están interrelacionadas, especialmente en hogares (hbroad, hiacc, iuse) y empresas digitalmente avanzadas (eweb, esocmedia). El acceso a Internet en los hogares y su banda ancha están claramente relacionados con el uso de Internet en la población. Las ventas electrónicas (esales) muestran una correlación más débil, sugiriendo que las infraestructuras digitales son necesarias pero no suficientes para garantizar altos niveles de adopción de e-commerce.</p>
</section>
<section id="apartado-b" class="level3">
<h3 class="anchored" data-anchor-id="apartado-b">Apartado b</h3>
<p><strong>Realizad una reducción del número de variables utilizando un Análisis de Componentes Principales (PCA). Justificad si trabajaréis con la matriz de covarianzas o la de correlaciones, considerando las características de los datos. Evaluad la idoneidad de la reducción propuesta, indicando claramente el criterio empleado para seleccionar el número de componentes principales a retener. Finalmente, interpretad las componentes principales seleccionadas, describiendo qué representan en el contexto de los datos y cómo contribuyen al análisis.</strong></p>
<p>Sabemos que la matriz de covarianzas se utiliza cuando las variables tienen las mismas unidades de medida y la misma escala. Recordemos que la covarianza mide la relación lineal entre las variables, pero no está normalizada. Esto significa que la covarianza depende de las unidades de las variables, por lo que puede ser más difícil de interpretar si las variables tienen escalas muy diferentes. Por otro lado, la matriz de correlaciones se utiliza cuando las variables tienen diferentes unidades de medida o rangos de valores muy distintos. En este caso, las variables de interés están en porcentaje pero las escalas de las variables pueden variar. Enotnces, trabajamos con la matriz de correlaciones. Esto asegura que las variables sean comparables y que los componentes principales no estén sesgados por las escalas de las variables.</p>
<p>Seleccionamos solo las variables numéricas, otra vez y estándarizar los datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data_standardized <span class="ot">&lt;-</span> <span class="fu">scale</span>(data_numeric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Realizemos el PCA</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pca_result <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(data_standardized, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Los valores propios muestran el porcentaje de varianza explicado por cada componente principal:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_eigenvalue</span>(pca_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      eigenvalue variance.percent cumulative.variance.percent
Dim.1 4.64389223       66.3413175                    66.34132
Dim.2 1.10116015       15.7308594                    82.07218
Dim.3 0.54694711        7.8135301                    89.88571
Dim.4 0.32755960        4.6794228                    94.56513
Dim.5 0.19113964        2.7305663                    97.29570
Dim.6 0.12374504        1.7677862                    99.06348
Dim.7 0.06555623        0.9365176                   100.00000</code></pre>
</div>
</div>
<p>Observamos que las dos primeras componentes principales explican aproximadamente el 81% de la variación total. Puede ser razonable, trabajar con esas dos componentes para el análisis posterior de estos datos.</p>
<p>Un método alternativo para determinar el número de componentes principales es observar el diagrama de valores propios ordenados de mayor a menor. El número de componentes se determina en el punto, más allá del cual los valores propios restantes son todos relativamente pequeños y de tamaño comparable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(pca_result, <span class="at">addlabels =</span> <span class="cn">TRUE</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica6_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>También podemos observar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(pca_result, <span class="at">col.var =</span> <span class="st">"contrib"</span>,<span class="at">repel =</span> <span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica6_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico anterior también se conoce como círculo de correlación variable. Muestra las relaciones entre todas las variables. Se puede interpretar de la siguiente manera:</p>
<ul>
<li><p>Las variables correlacionadas positivamente se agrupan.</p></li>
<li><p>Las variables correlacionadas negativamente se colocan en lados opuestos del origen de la trama (cuadrantes opuestos).</p></li>
<li><p>La distancia entre variables y el origen mide la calidad de la representación de las variables, las que están alejadas del origen están bien representadas.</p></li>
</ul>
<p>La calidad de representación de las variables se llama cos2 (coseno cuadrado, coordenadas cuadradas). Es posible crear un diagrama de barras de las variables cos2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>var <span class="ot">&lt;-</span> <span class="fu">get_pca_var</span>(pca_result)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cos2</span>(pca_result, <span class="at">choice =</span> <span class="st">"var"</span>, <span class="at">axes =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica6_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Un cos2 alto indica una buena representación de la variable en el componente principal. En este caso, la variable se coloca cerca de la circunferencia del círculo de correlación.</p></li>
<li><p>Un cos2 bajo indica que la variable no está perfectamente representada por los PC. En este caso, la variable está cerca del centro del círculo.</p></li>
</ul>
<p>El biplot es un gráfico que permite representar las variables originales y las observaciones transformadas en los ejes de componentes principales.</p>
<ul>
<li><p>Cada flecha corresponde a una variable.</p></li>
<li><p>Nos fijamos primeramente en las direcciones de las flechas y su sentido.</p></li>
<li><p>Dos flechas que apunten al mismo lugar indica correlación alta.</p></li>
<li><p>Dos flechas con sentidos diferentes pero en la misma dirección indican una correlación negativa.</p></li>
<li><p>Cuando dos variables no están correladas en absoluto, se observan dos flechas apuntando en direcciones totalmente perpendiculares.</p></li>
<li><p>En cuanto a la diferencia en la longitud de las flechas, una menos larga informa que su variable está peor representada que una de largo mayor. Es una forma de medir la calidad de representación.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_biplot</span>(pca_result, <span class="at">repel =</span> <span class="cn">TRUE</span>,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">col.var =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"purple"</span>, <span class="st">"orange"</span>, <span class="st">"yellow"</span>, <span class="st">"pink"</span>),</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">col.ind =</span> <span class="st">"#696969"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica6_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el gràfico anterior podemos observar lo siguiente:</p>
<ul>
<li><p>Todas las variables originales tienen influencia en las componentes principales, como lo demuestra la presencia de flechas para cada una de las variables.</p></li>
<li><p>La variable que tienen una flecha más larga, tiene un impacto considerable en la primera componente principal (Dim1).</p></li>
<li><p>La variable hbroad tiene una flecha en dirección similar a 45 grados entre las dos variables, mostrando que influye tanto en Dim1 como en Dim2.</p></li>
<li><p>Las variables como eweb y esocmedia están más asociadas con Dim2, dado que sus flechas tienen un ángulo cercano a la vertical.</p></li>
<li><p>esales está más alineada con la Dim1</p></li>
<li><p>Variables como hbroad y hiacc tienen influencia en ambas dimensiones, ya que sus flechas no están alineadas completamente con ninguna de las dos componentes principales.</p></li>
<li><p>Las observaciones se distribuyen principalmente a lo largo de Dim1 (que explica el 66.3% de la varianza), indicando que esta dimensión capta la mayor parte de las diferencias entre las observaciones.</p></li>
<li><p>Observaciones como la 2, 15 y 11 se destacan en el lado positivo de Dim1, lo que puede sugerir altos valores en variables asociadas como esales.</p></li>
<li><p>La observación 16 se encuentra en el extremo negativo de Dim1, lo que indica valores bajos en las variables que contribuyen positivamente a esta dimensión.</p></li>
<li><p>La segunda componente principal (Dim2), que explica el 15.7% de la varianza, parece separar moderadamente las observaciones con base en variables como eweb y esocmedia, aunque su contribución es menor en comparación con Dim1.</p></li>
<li><p>En general, el gráfico muestra que la primera componente principal (Dim1) domina al explicar la mayor parte de la variabilidad en los datos, mientras que la segunda componente (Dim2) capta patrones adicionales en las variables relacionadas con la interacción web y los medios sociales (eweb, esocmedia).</p></li>
</ul>
</section>
<section id="problema-2" class="level2">
<h2 class="anchored" data-anchor-id="problema-2">Problema 2</h2>
<p><strong>El metabolismo se caracteriza por reacciones químicas vinculadas entre sí, creando una compleja estructura de red. Una representación simplificada del metabolismo, que denominamos red metabólica abstracta, es un grafo en el que las vías metabólicas son nodos y existe una arista entre dos nodos si sus correspondientes vías comparten uno o más compuestos.</strong></p>
<p><strong>Para explorar los potenciales y límites de una representación tan básica, hemos empleado tres tipos de kernels (distancias entre grafos):</strong></p>
<ul>
<li><p>VH (Vertex histogram): solo tiene en cuenta si las etiquetas de los nodos de los grafos que se comparan son iguales o no.</p></li>
<li><p>SP (Shortest-Path): compara los grafos en función de sus caminos más cortos. Intuitivamente, esto significa medir lo fácil o difícil que es conectar, a través de compuestos compartidos, parejas de caminos en los dos grafos.</p></li>
<li><p>PM (Pyramid Match): mide la similitud de las características topológicas (por ejemplo, la conectividad) de los nodos con la misma etiqueta en los dos grafos comparados.</p></li>
</ul>
<p><strong>La práctica consiste en representar gráficamente (con solo 2 coordenadas principales) las matrices de similitud generadas por cada kernel coloreando los puntos de acuerdo al grupo de animales de acuerdo a su phylum.</strong></p>
<p><strong>Los ficheros necesarios para realizar la práctica los podéis descargar de la página del curso en Aula Digital.</strong></p>
<p>Carga los datos:</p>
<ul>
<li>Cargar las matrices de similitud:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sim_matrix_vh <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">read.table</span>(<span class="st">"ANIMALS-matrixVH.txt"</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>sim_matrix_sp <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">read.table</span>(<span class="st">"ANIMALS-matrixSP.txt"</span>))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>sim_matrix_pm <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">read.table</span>(<span class="st">"ANIMALS-matrixPM.txt"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Cargar los phylums</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>phylum_data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"fileListANIMAL_phylum.txt"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>phylums <span class="ot">&lt;-</span> phylum_data<span class="sc">$</span>V2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Utilizamos MDS para la reducción de dimensión:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mds_vh <span class="ot">&lt;-</span> <span class="fu">cmdscale</span>(<span class="fu">as.dist</span>(<span class="dv">1</span> <span class="sc">-</span> sim_matrix_vh), <span class="at">k =</span> <span class="dv">2</span>) </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>mds_sp <span class="ot">&lt;-</span> <span class="fu">cmdscale</span>(<span class="fu">as.dist</span>(<span class="dv">1</span> <span class="sc">-</span> sim_matrix_sp), <span class="at">k =</span> <span class="dv">2</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>mds_pm <span class="ot">&lt;-</span> <span class="fu">cmdscale</span>(<span class="fu">as.dist</span>(<span class="dv">1</span> <span class="sc">-</span> sim_matrix_pm), <span class="at">k =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Visualización:</p>
<section id="gráfico-para-vh" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-para-vh">Gráfico para VH</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df_vh <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">PC1 =</span> mds_vh[, <span class="dv">1</span>], <span class="at">PC2 =</span> mds_vh[, <span class="dv">2</span>], <span class="at">Phylum =</span> phylums)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>plot_vh <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_vh, <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">color =</span> Phylum)) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"MDS - Kernel VH"</span>, <span class="at">x =</span> <span class="st">"Dim 1"</span>, <span class="at">y =</span> <span class="st">"Dim 2"</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>plot_vh</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica6_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gráfico-para-sp" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-para-sp">Gráfico para SP</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>df_sp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">PC1 =</span> mds_sp[, <span class="dv">1</span>], <span class="at">PC2 =</span> mds_sp[, <span class="dv">2</span>], <span class="at">Phylum =</span> phylums)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>plot_sp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_sp, <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">color =</span> Phylum)) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"MDS - Kernel SP"</span>, <span class="at">x =</span> <span class="st">"Dim 1"</span>, <span class="at">y =</span> <span class="st">"Dim 2"</span>) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>plot_sp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica6_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gráfico-para-pm" class="level3">
<h3 class="anchored" data-anchor-id="gráfico-para-pm">Gráfico para PM</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_pm <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">PC1 =</span> mds_pm[, <span class="dv">1</span>], <span class="at">PC2 =</span> mds_pm[, <span class="dv">2</span>], <span class="at">Phylum =</span> phylums)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>plot_pm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_pm, <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">color =</span> Phylum)) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"MDS - Kernel PM"</span>, <span class="at">x =</span> <span class="st">"Dim 1"</span>, <span class="at">y =</span> <span class="st">"Dim 2"</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>plot_pm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="practica6_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>